---
version: '3.8'
services:
  po-create-processor:
    image: praveenbelkar/po-create-processor
    ports:
      - 80:8080
    environment:
      QUARKUS_KAFKA_STREAMS_APPLICATION_ID: "${APPLICATION_ID}"
      QUARKUS_KAFKA_STREAMS_BOOTSTRAP_SERVERS: "${BOOTSTRAP_SERVERS}"
      QUARKUS_KAFKA_STREAMS_SCHEMA_REGISTRY_URL: "${SCHEMA_REGISTRY_URL}"
      QUARKUS_KAFKA_STREAMS_SASL_JAAS_CONFIG: "${SASL_JAAS_CONFIG}"
      QUARKUS_KAFKA_STREAMS_SASL_MECHANISM: "${SASL_MECHANISM}"
      QUARKUS_KAFKA_STREAMS_SECURITY_PROTOCOL: "${SECURITY_PROTOCOL}"
      QUARKUS_KAFKA_STREAMS_SSL_TRUSTSTORE_LOCATION: "${SSL_TRUSTSTORE_LOCATION}"
      QUARKUS_KAFKA_STREAMS_SSL_TRUSTSTORE_PASSWORD: "${SSL_TRUSTSTORE_PASSWORD}"
      QUARKUS_KAFKA_STREAMS_SSL_TRUSTSTORE_TYPE: "${SSL_TRUSTSTORE_TYPE}"
      KAFKA_STREAMS_AUTO_REGISTER_SCHEMAS: "${AUTO_REGISTER_SCHEMAS}"
      SCHEMA_USER: "${SCHEMA_USER}"
      SCHEMA_PASS: "${SCHEMA_PASS}"
      PO_CREATE_INBOUND_JSON_TOPIC: "${PO_CREATE_INBOUND_JSON_TOPIC}"
      PO_CREATE_INBOUND_SAP_AVRO_TOPIC: "${PO_CREATE_INBOUND_SAP_AVRO_TOPIC}"
      PO_ERROR_TOPIC: "${PO_ERROR_TOPIC}"
      SUBJECT_PO_CREATE_INBOUND_JSON: "${SUBJECT_PO_CREATE_INBOUND_JSON}"
      SUBJECT_PO_CREATE_INBOUND_SAP_AVRO: "${SUBJECT_PO_CREATE_INBOUND_SAP_AVRO}"
      NEW_RELIC_APP_NAME: "${NEW_RELIC_APP_NAME}"
      NEW_RELIC_LICENSE_KEY: "${NEW_RELIC_LICENSE_KEY}"
    volumes:
      - ./truststore:/etc/truststore